import styles from './Layout.module.scss';
import React from "react";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { Inter } from 'next/font/google';
import Head from "next/head";
const inter = Inter({ subsets: ['cyrillic', 'latin'] })

const Layout = ({ children }:{children: React.ReactNode}) => {
	return(
		<>
		<Head>
			<title>Create Next App</title>
			<meta name="description" content="Generated by create next app" />
			<meta name="viewport" content="width=device-width, initial-scale=1" />
			<link rel="icon" href="/favicon.ico" />
		</Head>
		<div className={`${styles.container} ${inter.className}`}>
			<Header/>
				{children}<main></main>
			<Footer/>
		</div>
		</>
	);
};

export default Layout;
